export const ActionConstants = {
	LOADING:"LOADING",
	STOP_LOADING:"STOP_LOADING",
	FETCH_SUCCESS:"FETCH_SUCCESS",
	FETCH_FAILED:"FETCH_FAILED",
	ADD_SUCCESS:"ADD_SUCCESS",
	ADD_FAILED:"ADD_FAILED",
	REMOVE_SUCCESS:"REMOVE_SUCCESS",
	REMOVE_FAILED:"REMOVE_FAILED"
}